"""
This module contains mappings between human-readable values and their corresponding codes
used in the FORM15CB XML.
"""

# Mapping for examiner prefix (I/We)
EXAMINER_PREFIX_MAP = {
    'I': '01',
    'We': '02'
}

# Mapping for remitter prefix (Mr/Ms/M/s)
REMITTER_PREFIX_MAP = {
    'Mr': '01',
    'Ms': '02',
    'M/s': '03'
}

# Mapping for beneficiary prefix
BENEFICIARY_PREFIX_MAP = {
    'Mr': '01',
    'Ms': '02',
    'M/s': '03'
}

# Mapping for countries (ISO 3166-1 alpha-2 codes)
# This is a subset of common countries - can be expanded
COUNTRY_MAP = {
    'Afghanistan': '93',
    'Albania': '355',
    'Algeria': '213',
    'Andorra': '376',
    'Angola': '244',
    'Argentina': '54',
    'Armenia': '374',
    'Australia': '61',
    'Austria': '43',
    'Azerbaijan': '994',
    'Bahamas': '1242',
    'Bahrain': '973',
    'Bangladesh': '880',
    'Barbados': '1246',
    'Belarus': '375',
    'Belgium': '32',
    'Belize': '501',
    'Benin': '229',
    'Bhutan': '975',
    'Bolivia': '591',
    'Bosnia and Herzegovina': '387',
    'Botswana': '267',
    'Brazil': '55',
    'Brunei': '673',
    'Bulgaria': '359',
    'Burkina Faso': '226',
    'Burundi': '257',
    'Cambodia': '855',
    'Cameroon': '237',
    'Canada': '1',
    'Cape Verde': '238',
    'Central African Republic': '236',
    'Chad': '235',
    'Chile': '56',
    'China': '86',
    'Colombia': '57',
    'Comoros': '269',
    'Congo (Brazzaville)': '242',
    'Congo (Kinshasa)': '243',
    'Costa Rica': '506',
    'Croatia': '385',
    'Cuba': '53',
    'Cyprus': '357',
    'Czech Republic': '420',
    'Denmark': '45',
    'Djibouti': '253',
    'Dominica': '1767',
    'Dominican Republic': '1809',
    'Ecuador': '593',
    'Egypt': '20',
    'El Salvador': '503',
    'Equatorial Guinea': '240',
    'Eritrea': '291',
    'Estonia': '372',
    'Eswatini': '268',
    'Ethiopia': '251',
    'Fiji': '679',
    'Finland': '358',
    'France': '33',
    'Gabon': '241',
    'Gambia': '220',
    'Georgia': '995',
    'Germany': '49',
    'Ghana': '233',
    'Greece': '30',
    'Grenada': '1473',
    'Guatemala': '502',
    'Guinea': '224',
    'Guinea-Bissau': '245',
    'Guyana': '592',
    'Haiti': '509',
    'Honduras': '504',
    'Hungary': '36',
    'Iceland': '354',
    'India': '91',
    'Indonesia': '62',
    'Iran': '98',
    'Iraq': '964',
    'Ireland': '353',
    'Israel': '972',
    'Italy': '39',
    'Jamaica': '1876',
    'Japan': '81',
    'Jordan': '962',
    'Kazakhstan': '7',
    'Kenya': '254',
    'Kiribati': '686',
    'Korea, North': '850',
    'Korea, South': '82',
    'Kuwait': '965',
    'Kyrgyzstan': '996',
    'Laos': '856',
    'Latvia': '371',
    'Lebanon': '961',
    'Lesotho': '266',
    'Liberia': '231',
    'Libya': '218',
    'Liechtenstein': '423',
    'Lithuania': '370',
    'Luxembourg': '352',
    'Madagascar': '261',
    'Malawi': '265',
    'Malaysia': '60',
    'Maldives': '960',
    'Mali': '223',
    'Malta': '356',
    'Marshall Islands': '692',
    'Mauritania': '222',
    'Mauritius': '230',
    'Mexico': '52',
    'Micronesia': '691',
    'Moldova': '373',
    'Monaco': '377',
    'Mongolia': '976',
    'Montenegro': '382',
    'Morocco': '212',
    'Mozambique': '258',
    'Myanmar': '95',
    'Namibia': '264',
    'Nauru': '674',
    'Nepal': '977',
    'Netherlands': '31',
    'New Zealand': '64',
    'Nicaragua': '505',
    'Niger': '227',
    'Nigeria': '234',
    'North Macedonia': '389',
    'Norway': '47',
    'Oman': '968',
    'Pakistan': '92',
    'Palau': '680',
    'Panama': '507',
    'Papua New Guinea': '675',
    'Paraguay': '595',
    'Peru': '51',
    'Philippines': '63',
    'Poland': '48',
    'Portugal': '351',
    'Qatar': '974',
    'Romania': '40',
    'Russia': '7',
    'Rwanda': '250',
    'Saint Kitts and Nevis': '1869',
    'Saint Lucia': '1758',
    'Saint Vincent and the Grenadines': '1784',
    'Samoa': '685',
    'San Marino': '378',
    'Sao Tome and Principe': '239',
    'Saudi Arabia': '966',
    'Senegal': '221',
    'Serbia': '381',
    'Seychelles': '248',
    'Sierra Leone': '232',
    'Singapore': '65',
    'Slovakia': '421',
    'Slovenia': '386',
    'Solomon Islands': '677',
    'Somalia': '252',
    'South Africa': '27',
    'South Sudan': '211',
    'Spain': '34',
    'Sri Lanka': '94',
    'Sudan': '249',
    'Suriname': '597',
    'Sweden': '46',
    'Switzerland': '41',
    'Syria': '963',
    'Taiwan': '886',
    'Tajikistan': '992',
    'Tanzania': '255',
    'Thailand': '66',
    'Timor-Leste': '670',
    'Togo': '228',
    'Tonga': '676',
    'Trinidad and Tobago': '1868',
    'Tunisia': '216',
    'Turkey': '90',
    'Turkmenistan': '993',
    'Tuvalu': '688',
    'Uganda': '256',
    'Ukraine': '380',
    'United Arab Emirates': '971',
    'United Kingdom': '44',
    'United States': '2',
    'Uruguay': '598',
    'Uzbekistan': '998',
    'Vanuatu': '678',
    'Vatican City': '379',
    'Venezuela': '58',
    'Vietnam': '84',
    'Yemen': '967',
    'Zambia': '260',
    'Zimbabwe': '263'
}

# Mapping for currencies (ISO 4217 codes)
# This is a subset of common currencies - can be expanded
CURRENCY_MAP = {
    'INR': '1',
    'USD': '2',
    'EUR': '3',
    'GBP': '4',
    'AUD': '5',
    'CAD': '6',
    'JPY': '7',
    'SGD': '8',
    'AED': '9',
    'SAR': '10'
}

# Bank name to code mapping
BANK_MAP = {
    'Abhyudaya Cooperative Bank': '1',
    'Abu Dhabi Commercial Bank': '2',
    'Ahmedabad Mercantile Cooperative Bank': '3',
    'Akola Janata Commercial Cooperative Bank': '4',
    'Allahabad Bank': '5',
    'Almora Urban Co-Operative Bank ltd': '6',
    'Andhra Bank': '7',
    'Andhra Pragathi Grameena Bank': '8',
    'Apna Sahakari Bank Ltd': '9',
    'Australia and New Zealand Banking Group Ltd': '10',
    'Axis Bank': '11',
    'Bank Internasional Indonesia': '12',
    'Bank of America': '13',
    'Bank of Bahrain and Kuwait': '14',
    'Bank of Baroda': '15',
    'Bank of Ceylon': '16',
    'Bank of India': '17',
    'Bank of Maharashtra': '18',
    'MUFG Bank Ltd': '19',
    'Barclays Bank': '20',
    'Bassein Catholic Co-Op Bank Ltd': '21',
    'Bharat Cooperative Bank Mumbai Ltd': '22',
    'Bharatiya Mahila Bank Ltd': '23',
    'BNP Paribas Bank': '24',
    'Canara Bank': '25',
    'Capital Local Area Bank Ltd': '26',
    'Catholic Syrian Bank': '27',
    'Central Bank of India': '28',
    'Chinatrust Commercial Bank': '29',
    'CITI Bank': '30',
    'Citizen Credit Cooperative Bank': '31',
    'City Union Bank Ltd': '32',
    'Commonwealth Bank of Australia': '33',
    'Corporation Bank': '34',
    'Credit Agricole Corporate and Investment Bank': '35',
    'Credit Suisse AG': '36',
    'DBS Bank Ltd': '37',
    'DCB Bank Ltd': '38',
    'Dena Bank': '39',
    'Deposit Insurance and Credit Guarantee Corporat': '40',
    'Deutsche Bank': '41',
    'Dhanlaxmi Bank Ltd': '42',
    'DICGC': '43',
    'Doha Bank QSC': '44',
    'Dombivli Nagari Sahakari Bank Ltd': '45',
    'Export Import Bank of India': '46',
    'Federal Bank Ltd': '47',
    'Firstrand Bank Ltd': '48',
    'G P Parsik Bank': '49',
    'Gurgaon Gramin Bank Ltd': '50',
    'HDFC Bank Ltd': '51',
    'HSBC': '52',
    'HSBC Bank Oman Saog': '53',
    'ICICI Bank Ltd': '54',
    'IDBI Ltd': '55',
    'Indian Bank': '56',
    'Indian Overseas Bank': '57',
    'Indusind Bank Ltd': '58',
    'Industrial and Commercial Bank of China Ltd': '59',
    'ING Vysya Bank Ltd': '60',
    'Jalgaon Janata Sahakari Bank Ltd': '61',
    'Janakalyan Sahakari Bank Ltd': '62',
    'Janaseva Sahakari Bank (Borivli) Ltd': '63',
    'Janaseva Sahakari Bank Ltd': '64',
    'Janata Sahakari Bank Ltd (Pune)': '65',
    'Jankalyan Sahakari Bank Ltd': '66',
    'JP Morgan Chase Bank NA': '67',
    'Kallappanna Awade Ichalkaranji Janata Sahakari B': '68',
    'Kalupur Commercial Cooperative Bank': '69',
    'Kapol Cooperative Bank': '70',
    'Karnataka Bank Ltd': '71',
    'Karnataka Vikas Grameena Bank': '72',
    'Karur Vysya Bank': '73',
    'Kerala Gramin Bank': '74',
    'Kotak Mahindra Bank': '75',
    'Laxmi Vilas Bank': '76',
    'Mahanagar Cooperative Bank Ltd': '77',
    'Maharastra State Cooperative Bank': '78',
    'Mashreq Bank': '79',
    'Mizuho Corporate Bank Ltd': '80',
    'Nagar Urban Co-Operative Bank': '81',
    'Nagpur Nagrik Sahakari Bank Ltd': '82',
    'National Australia Bank': '83',
    'New India Cooperative Ban Ltd': '84',
    'NKGSB Cooperative Bank Ltd': '85',
    'North Malabar Gramin Bank': '86',
    'Nutan Nagarik Sahakari Bank Ltd': '87',
    'Oman International Bank': '88',
    'Oriental Bank of Commerce': '89',
    'Pragathi Krishna Gramin Bank': '90',
    'Prathama Bank': '91',
    'Prime Co-Operative Bank Ltd': '92',
    'Punjab and Maharashtra Cooperative Bank Ltd': '93',
    'Punjab and Sind Bank': '94',
    'Punjab National Bank': '95',
    'Rabobank International': '96',
    'Rajgurunagar Sahakari Bank Ltd': '97',
    'Rajkot Nagarik Sahakari Bank Ltd': '98',
    'Ratnakar Bank Ltd': '99',
    'Reserve Bank of India': '100',
    'Sahebrao Deshmukh Co-Op. Bank Ltd': '101',
    'SBER Bank': '102',
    'Shikshak Sahakari Bank Ltd': '103',
    'Shinhan Bank': '104',
    'Shri Chhatrapati Rajarshi Shahu Urban Co-Op Ban': '105',
    'Societe Generale': '106',
    'Solapur Janata Sahakari Bank Ltd': '107',
    'South Indian Bank': '108',
    'Standard Chartered Bank': '109',
    'State Bank of Bikaner and Jaipur': '110',
    'State Bank of Hyderabad': '111',
    'State Bank of India': '112',
    'SBM Bank (India) Limited': '113',
    'State Bank of Mysore': '114',
    'State Bank of Patiala': '115',
    'State Bank of Travancore': '116',
    'Sumitomo Mitsui Banking Corporation': '117',
    'Sutex Cooperative Bank Ltd': '118',
    'Syndicate Bank': '119',
    'Tamil Nadu Mercantile Bank': '120',
    'The A.P. Mahesh Co-Op Urban Bank Ltd': '121',
    'The Akola District Central Co-Operative Bank': '122',
    'The Andhra Pradesh State Coop Bank Ltd': '123',
    'The Bank of Nova Scotia': '124',
    'The Cosmos Cooperative Bank Ltd': '125',
    'The Delhi State Cooperative Bank Ltd': '126',
    'The Gadchiroli District Central Cooperative Bank L': '127',
    'The Greater Bombay Co-operative Bank Ltd': '128',
    'The Gujarat State Co-Operative Bank Ltd': '129',
    'The Jalgaon Peoples Co-Op Bank': '130',
    'The Jammu and Kashmir Bank': '131',
    'The Kalyan Janata Sahakari Bank Ltd': '132',
    'The Kangra Central Cooperative Bank Ltd': '133',
    'The Kangra Cooperative Bank Ltd': '134',
    'The Karad Urban Co-op Bank Ltd': '135',
    'The Karnataka State Apex Cooperative Bank Ltd': '136',
    'The Kurmanchal Nagar Sahkari Bank Ltd': '137',
    'The Mehsana Urban Cooperative Bank Ltd': '138',
    'The Mumbai District Central Co-Op Bank Ltd': '139',
    'The Municipal Co Operative Bank Ltd, Mumbai': '140',
    'The Nainital Bank Ltd': '141',
    'The Nasik Merchants Co-Op Bank Ltd': '142',
    'The Rajasthan State Cooperative Bank Ltd': '143',
    'The Royal Bank of Scotland N.V.': '144',
    'The Saraswat Cooperative Bank Ltd': '145',
    'The Seva Vikas Co-Operative Bank Ltd': '146',
    'The Shamrao Vithal Cooperative Bank Ltd': '147',
    'The Surat District Co Operative Bank Ltd': '148',
    'The Surat Peoples Co-Op Bank Ltd': '149',
    'The Tamilnadu State Apex Cooperative Bank': '150',
    'The Thane Bharat Sahakari Bank Ltd': '151',
    'The Thane District Central Co-Op Bank Ltd': '152',
    'The Varachha Co-Op. Bank Ltd': '153',
    'The Vishweshwar Sahakari Bank Ltd': '154',
    'The West Bengal State Cooperative Bank Ltd': '155',
    'The Zoroastrian Cooperative Bank Limited': '156',
    'TJSB Sahakari Bank Ltd': '157',
    'Tumkur Grain Merchants Cooperative Bank Ltd': '158',
    'UCO Bank': '159',
    'Union Bank of India': '160',
    'United Bank of India': '161',
    'United Overseas Bank': '162',
    'Vasai Vikas Sahakari Bank Ltd': '163',
    'Vijaya Bank': '164',
    'Westpac Banking Corporation': '165',
    'Woori Bank': '166',
    'Yes Bank Ltd': '167',
    'Zila Sahakari Bank Ltd Ghaziabad': '168',
    'The HASTI Co-Operative Bank Ltd': '169',
    'Bandhan Bank Limited': '170',
    'IDFC Bank Limited': '171',
    'Industrial Bank of Korea': '172',
    'National Bank of Abu Dhabi PJSC': '173',
    'Surat National Cooperative Bank Limited': '174',
    'Other Bank': '175'
}

# Mapping for nature of remittance categories
NATURE_REM_CATEGORY_MAP = {
    'ADVERTISEMENT FEE': '16.1',
    'AMC CHARGES': '16.2',
    'ARCHITECTURAL SERVICES': '16.3',
    'BANDWIDTH CHARGES': '16.4',
    'BROKERAGE CHARGES': '16.5',
    'BUSINESS INCOME OTHER THAN THAT COVERED BY CATEGORIES ABOVE': '16.6',
    'CARGO HANDLING SERVICES INSPECTION & LOGISTICS SERVICES': '16.7',
    'CELLULAR ROAMING CHARGES': '16.8',
    'CHARTER HIRE CHARGES (SHIPPING)': '16.9',
    'CLEARING & FORWARDING CHARGES': '16.10',
    'COMMISSION': '16.11',
    'COMMUNICATION CHARGES': '16.12',
    'CONSULTING SERVICES': '16.13',
    'DESIGNING FEE': '16.14',
    'DIRECTORS FEES': '16.15',
    'DIVIDEND': '16.16',
    'DRILLING': '16.17',
    'ENGINEERING SERVICES': '16.18',
    'EQUIPMENT RENTAL CHARGES': '16.19',
    'FABRICATION SERVICES': '16.20',
    'FEES FOR TECHNICAL SERVICES/ FEES FOR INCLUDED SERVICES': '16.21',
    'FREIGHT CHARGES': '16.22',
    'INCOME FROM IMMOVEABLE PROPERTY': '16.23',
    'INCOME FROM SHIPPING, INLAND WATERWAYS OR AIR TRANSPORT': '16.24',
    'INSTALLATION & COMMISSIONING SERVICES': '16.25',
    'INSURANCE COMMISSIONS': '16.26',
    'INTEREST PAYMENT': '16.27',
    'INVESTMENT INCOME': '16.28',
    'LEASE PAYMENT': '16.29',
    'LICENSING FEE': '16.30',
    'LONG TERM CAPITAL GAINS': '16.31',
    'MEMBERSHIP FEE': '16.32',
    'MOBILESTATION CHARGES': '16.33',
    'PAYMENTS FOR SOFTWARE BUNDLED WITH HARDWARE': '16.34',
    'PAYMENTS TO PROFESSORS, TEACHERS OR RESEARCH SCHOLARS': '16.35',
    'PAYMENTS TO SPORTS PERSON & ARTISTS': '16.36',
    'PAYMENTS TO STUDENTS OR BUSINESS APPRENTICE': '16.37',
    'PENSIONS(OTHER THAN THOSE RELATED TO PAST EMPLOYMENT)': '16.38',
    'PROCESSING CHARGES': '16.39',
    'PROFESSIONAL SERVICES': '16.40',
    'PURCHASE OF SOFTWARE': '16.41',
    'R&D CHARGES': '16.42',
    'REGISTRATION CHARGES': '16.43',
    'REIMBURSEMENT OF EXPENSES': '16.44',
    'REPATRIATION OF SURPLUS FUNDS': '16.45',
    'RETAINERSHIP FEES': '16.46',
    'RETENTION FEES': '16.47',
    'ROYALTY': '16.48',
    'SALES AND MARKETING SERVICES': '16.49',
    'SEISMIC DATA PROCESSING': '16.50',
    'SHORT TERM CAPITAL GAINS': '16.51',
    'SOFTWARE LICENCES': '16.52',
    'SPONSORSHIP FEES': '16.53',
    'SUBSCRIPTION FEES': '16.54',
    'SUPERVISION CHARGES': '16.55',
    'SURVEY FEES': '16.56',
    'TELECASTING SERVICES': '16.57',
    'TENDER FEES': '16.58',
    'TESTING CHARGES': '16.59',
    'TRAINING': '16.60',
    'WARRANTY SERVICES': '16.61',
    'WINNING FROM HORSE RACES.': '16.62',
    'WINNING FROM LOTTERIES, CROSSWORD PUZZLES, CARD GAMES AND OTHER GAMES OF ANY SORT.': '16.63',
    'CONSULAR RECEIPTS': '16.64',
    'OTHER INCOME / OTHER (NOT IN THE NATURE OF INCOME)': '16.65'
}

# Mapping for RBI Purpose Code Categories
RBI_PURPOSE_CATEGORY_MAP = {
    'RB-0.1': 'Capital Account',
    'RB-0.2': 'Foreign Direct Investments',
    'RB-0.3': 'Foreign Portfolio Investment',
    'RB-0.4': 'External Commercial Borrowings',
    'RB-0.5': 'Short term Loans',
    'RB-0.6': 'Banking Capital',
    'RB-0.7': 'Financial Derivatives and Others',
    'RB-0.8': 'External Assistance',
    'RB-1.1': 'Imports',
    'RB-2.1': 'Transport',
    'RB-3.1': 'Travel',
    'RB-5.1': 'Construction Services',
    'RB-6.1': 'Insurance and Pension Services',
    'RB-7.1': 'Financial Services',
    'RB-8.1': 'Telecommunication, Computer & Information Services',
    'RB-9.1': 'Charges for the use of intellectual property n.i.e',
    'RB-10.1': 'Other Business Services',
    'RB-11.1': 'Personal, Cultural & Recreational services',
    'RB-12.1': 'Govt. not included elsewhere (G.n.i.e.)',
    'RB-13.1': 'Secondary Income',
    'RB-14.1': 'Primary Income',
    'RB-15.1': 'Others',
    'RB-16.1': 'Maintenance and repair services n.i.e',
    'RB-17.1': 'Manufacturing services (goods for processing)'
}

# RBI Purpose Code Category to Specific Code mapping
RBI_PURPOSE_CODE_MAP = {
    'RB-0.1': {
        'RB-0.1-Select': 'Select',
        'RB-0.1-S0017': 'S0017 - Acquisition of non-produced non-financial assets (Purchase of intangible assets like patents, copyrights, trademarks etc. land acquired by government, use of natural resources)',
        'RB-0.1-S0019': 'S0019 - Acquisition of non-produced non-financial assets (Purchase of intangible assets like patents, copyrights, trademarks etc. use of natural resources) – Non-Government',
        'RB-0.1-S0099': 'S0099 - Other capital payments not included elsewhere',
        'RB-0.1-S0026': 'S0026 - Capital transfers (Guarantees payments, Investment Grand given by the Government/international organisation, exceptionally large Non-life insurance claims) – Government',
        'RB-0.1-S0027': 'S0027 - Capital transfers (Guarantees payments, Investment Grand given by the Non-government, exceptionally large Non-life insurance claims) –Non-Government'
    },
    'RB-0.2': {
        'RB-0.2-Select': 'Select',
        'RB-0.2-S0003': 'S0003 - Indian Direct investment abroad (in branches & wholly owned subsidiaries) in equity Shares',
        'RB-0.2-S0004': 'S0004 - Indian Direct investment abroad (in subsidiaries and associates) in debt instruments',
        'RB-0.2-S0005': 'S0005 - Indian investment abroad – in real estate',
        'RB-0.2-S0006': 'S0006 - Repatriation of Foreign Direct Investment made by overseas Investors in India – in equity share',
        'RB-0.2-S0007': 'S0007 - Repatriation of Foreign Direct Investment in made by overseas Investors India – in debt instrum',
        'RB-0.2-S0008': 'S0008 - Repatriation of Foreign Direct Investment made by overseas Investors in India – in real estate'
    },
    'RB-0.3': {
        'RB-0.3-Select': 'Select',
        'RB-0.3-S0001': 'S0001 - Indian Portfolio investment abroad –in equity shares',
        'RB-0.3-S0002': 'S0002 - Indian Portfolio investment abroad –in debt instruments',
        'RB-0.3-S0009': 'S0009 - Repatriation of Foreign Portfolio Investment made by overseas Investors in India – in equity shares',
        'RB-0.3-S0010': 'S0010 - Repatriation of Foreign Portfolio Investment made by overseas Investors in India – in debt instruments'
    },
    'RB-0.4': {
        'RB-0.4-Select': 'Select',
        'RB-0.4-S0011': 'S0011 - Loans extended to Non – Residents',
        'RB-0.4-S0012': 'S0012 - Repayment of long & medium term loans with original maturity above one year received from Non-Residents'
    },
    'RB-0.5': {
        'RB-0.5-Select': 'Select',
        'RB-0.5-S0013': 'S0013 - Repayment of short term loans with original maturity up to one year received from Non-Residents'
    },
    'RB-0.6': {
        'RB-0.6-Select': 'Select',
        'RB-0.6-S0014': 'S0014 - Repatriation of Non-Resident Deposits (FCNR(B)/NR(E)RA, etc.)',
        'RB-0.6-S0015': 'S0015 - Repayment of loans & overdrafts taken by ADs on their own',
        'RB-0.6-S0016': 'S0016 - Sale of a foreign currency against another foreign currency'
    },
    'RB-0.7': {
        'RB-0.7-Select': 'Select',
        'RB-0.7-S0020': 'S0020 - Payments made on account of margin payments, premium payment and settlement amount etc. under Financial derivative',
        'RB-0.7-S0021': 'S0021 - Payments made on account of sale of share under Employee stock option',
        'RB-0.7-S0022': 'S0022 - Investment in Indian Depositories Receipts (IDRs)',
        'RB-0.7-S0023': 'S0023 - Opening of foreign currency account abroad with a bank'
    },
    'RB-0.8': {
        'RB-0.8-Select': 'Select',
        'RB-0.8-S0024': 'S0024 - External Assistance extended by India. e.g. Loans and advances extended by India to Foreign governments under',
        'RB-0.8-S0025': 'S0025 - Repayments made on account of External Assistance received by India'
    },
    'RB-1.1': {
        'RB-1.1-Select': 'Select',
        'RB-1.1-S0101': 'S0101 - Advance payment against imports made to countries other than Nepal and Bhutan',
        'RB-1.1-S0102': 'S0102 - Payment towards imports-settlement of invoice other than Nepal and Bhutan',
        'RB-1.1-S0103': 'S0103 - Imports by diplomatic missions other than Nepal and Bhutan',
        'RB-1.1-S0104': 'S0104 - Intermediary trade/transit trade, i.e., third country export passing through India',
        'RB-1.1-S0108': 'S0108 - Goods acquired under merchanting / Payment against import leg of merchanting trade',
        'RB-1.1-S0109': 'S0109 - Payments made for Imports from Nepal and Bhutan, if any'
    },
    'RB-2.1': {
        'RB-2.1-Select': 'Select',
        'RB-2.1-S0201': 'S0201 - Payments for surplus freight/passenger fare by foreign shipping companies operating in India',
        'RB-2.1-S0202': 'S0202 - Payment for operating expenses of Indian shipping companies operating abroad',
        'RB-2.1-S0203': 'S0203 - Freight on imports –Shipping companies',
        'RB-2.1-S0204': 'S0204 - Freight on exports –Shipping companies',
        'RB-2.1-S0205': 'S0205 - Operational leasing/Rental of Vessels (with crew) –Shipping companies',
        'RB-2.1-S0206': 'S0206 - Booking of passages abroad –Shipping companies',
        'RB-2.1-S0207': 'S0207 - Payments for surplus freight/passenger fare by foreign Airlines companies operating in India',
        'RB-2.1-S0208': 'S0208 - Operating expenses of Indian Airlines companies operating',
        'RB-2.1-S0209': 'S0209 - Freight on imports –Airlines companies',
        'RB-2.1-S0210': 'S0210 - Freight on exports –Airlines companies',
        'RB-2.1-S0211': 'S0211 - Operational leasing / Rental of Vessels (with crew) –Airline companies',
        'RB-2.1-S0212': 'S0212 - Booking of passages abroad –Airlines companies',
        'RB-2.1-S0214': 'S0214 - Payments on account of stevedoring, demurrage, port handling charges etc.(Shipping companies)',
        'RB-2.1-S0215': 'S0215 - Payments on account of stevedoring, demurrage, port handling charges, etc.(Airlines companies)',
        'RB-2.1-S0216': 'S0216 - Payments for Passenger -Shipping companies',
        'RB-2.1-S0217': 'S0217 - Other payments by Shipping companies',
        'RB-2.1-S0218': 'S0218 - Payments for Passenger -Airlines companies',
        'RB-2.1-S0219': 'S0219 - Other Payments by Airlines companies',
        'RB-2.1-S0220': 'S0220 - Payments on account of freight under other modes of transport (Internal Waterways, Roadways, Railw',
        'RB-2.1-S0221': 'S0221 - Payments on account of passenger fare under other modes of transport (Internal Waterways, Roadwa',
        'RB-2.1-S0222': 'S0222 - Postal & Courier services by Air',
        'RB-2.1-S0223': 'S0223 - Postal & Courier services by Sea',
        'RB-2.1-S0224': 'S0224 - Postal & Courier services by others'
    },
    'RB-3.1': {
        'RB-3.1-Select': 'Select',
        'RB-3.1-S0301': 'S0301 - Business travel.',
        'RB-3.1-S0303': 'S0303 - Travel for pilgrimage',
        'RB-3.1-S0304': 'S0304 - Travel for medical treatment',
        'RB-3.1-S0305': 'S0305 - Travel for education (including fees, hostel expenses etc.)',
        'RB-3.1-S0306': 'S0306 - Other travel (including holiday trips and payments for settling international credit cards transactions)'
    },
    'RB-5.1': {
        'RB-5.1-Select': 'Select',
        'RB-5.1-S0501': 'S0501 - Construction of projects abroad by Indian companies including import of goods at project site abroad',
        'RB-5.1-S0502': 'S0502 - cost of construction etc. of projects executed by foreign companies in India.'
    },
    'RB-6.1': {
        'RB-6.1-Select': 'Select',
        'RB-6.1-S0601': 'S0601 - Life Insurance premium except term insurance',
        'RB-6.1-S0602': 'S0602 - Freight insurance –relating to import and export of goods',
        'RB-6.1-S0603': 'S0603 - Other general insurance premium including reinsurance premium; and term life insurance premium',
        'RB-6.1-S0605': 'S0605 - Auxiliary services including commission on insurance',
        'RB-6.1-S0607': 'S0607 - Insurance claim Settlement of non-life insurance; and life insurance (only term insurance)',
        'RB-6.1-S0608': 'S0608 - Life Insurance Claim Settlements',
        'RB-6.1-S0609': 'S0609 - Standardised guarantee services',
        'RB-6.1-S0610': 'S0610 - Premium for pension funds',
        'RB-6.1-S0611': 'S0611 - Periodic pension entitlements e.g. monthly quarterly or yearly payments of pension amounts by Indian Pension Fund',
        'RB-6.1-S0612': 'S0612 - Invoking of standardised guarantees'
    },
    'RB-7.1': {
        'RB-7.1-Select': 'Select',
        'RB-7.1-S0701': 'S0701 - Financial intermediation, except investment banking -Bank charges, collection charges, LC charges etc.',
        'RB-7.1-S0702': 'S0702 - Investment banking –brokerage, under writing commission',
        'RB-7.1-S0703': 'S0703 - Auxiliary services –charges on operation & regulatory fees, custodial services, depository services etc.'
    },
    'RB-8.1': {
        'RB-8.1-Select': 'Select',
        'RB-8.1-S0801': 'S0801 - Hardware consultancy/implementation',
        'RB-8.1-S0802': 'S0802 - Software consultancy / implementation',
        'RB-8.1-S0803': 'S0803 - Data base, data processing charges',
        'RB-8.1-S0804': 'S0804 - Repair and maintenance of computer and software',
        'RB-8.1-S0805': 'S0805 - News agency services',
        'RB-8.1-S0806': 'S0806 - Other information services-Subscription to newspapers,',
        'RB-8.1-S0807': 'S0807 - Off-site software imports',
        'RB-8.1-S0808': 'S0808 - Telecommunication services including electronic mail services and voice mail services',
        'RB-8.1-S0809': 'S0809 - Satellite services including space shuttle and rockets etc.'
    },
    'RB-9.1': {
        'RB-9.1-Select': 'Select',
        'RB-9.1-S0901': 'S0901 - Franchises services',
        'RB-9.1-S0902': 'S0902 - Payment for use, through licensing arrangements, of produced originals or prototypes (such as manuscripts and films), patents, copyrights, trademarks and industrial processes etc.'
    },
    'RB-10.1': {
        'RB-10.1-Select': 'Select',
        'RB-10.1-S1002': 'S1002 - Trade related services –commission on exports / imports',
        'RB-10.1-S1003': 'S1003 - Operational leasing services (other than financial leasing) without operating crew, including charter hire- Airlines companies',
        'RB-10.1-S1004': 'S1004 - Legal services',
        'RB-10.1-S1005': 'S1005 - Accounting, auditing, book-keeping services',
        'RB-10.1-S1006': 'S1006 - Business and management consultancy and public relations',
        'RB-10.1-S1007': 'S1007 - Advertising, trade fair service',
        'RB-10.1-S1008': 'S1008 - Research & Development services',
        'RB-10.1-S1009': 'S1009 - Architectural services',
        'RB-10.1-S1010': 'S1010 - Agricultural services like protection against insects & disease, increasing of harvest yields, forestry services.',
        'RB-10.1-S1011': 'S1011 - Payments for maintenance of offices abroad',
        'RB-10.1-S1013': 'S1013 - Environmental Services',
        'RB-10.1-S1014': 'S1014 - Engineering Services',
        'RB-10.1-S1015': 'S1015 - Tax consulting services',
        'RB-10.1-S1016': 'S1016 - Market research and public opinion polling service',
        'RB-10.1-S1017': 'S1017 - Publishing and printing services',
        'RB-10.1-S1018': 'S1018 - Mining services like on –site processing services analysis of ores etc.',
        'RB-10.1-S1020': 'S1020 - Commission agent services',
        'RB-10.1-S1021': 'S1021 - Wholesale and retailing trade services.',
        'RB-10.1-S1022': 'S1022 - Operational leasing services (other than financial leasing) without operating crew, including charter hire- Shipping companies',
        'RB-10.1-S1023': 'S1023 - Other Technical Services including scientific/space services.',
        'RB-10.1-S1099': 'S1099 - Other services not included elsewhere'
    },
    'RB-11.1': {
        'RB-11.1-Select': 'Select',
        'RB-11.1-S1101': 'S1101 - Audio-visual and related services like Motion picture and video tape production, distribution and projection services.',
        'RB-11.1-S1103': 'S1103 - Radio and television production, distribution and transmission services',
        'RB-11.1-S1104': 'S1104 - Entertainment services',
        'RB-11.1-S1105': 'S1105 - Museums, library and archival services',
        'RB-11.1-S1106': 'S1106 - Recreation and sporting activities services',
        'RB-11.1-S1107': 'S1107 - Education (e.g. fees for correspondence courses abroad)',
        'RB-11.1-S1108': 'S1108 - Health Service (payment towards services received from hospitals, doctors, nurses, paramedical and similar services etc. rendered remotely or on-site)',
        'RB-11.1-S1109': 'S1109 - Other Personal, Cultural & Recreational services'
    },
    'RB-12.1': {
        'RB-12.1-Select': 'Select',
        'RB-12.1-S1201': 'S1201 - Maintenance of Indian embassies abroad',
        'RB-12.1-S1202': 'S1202 - Remittances by foreign embassies in India'
    },
    'RB-13.1': {
        'RB-13.1-Select': 'Select',
        'RB-13.1-S1301': 'S1301 - Remittance for family maintenance and savings',
        'RB-13.1-S1302': 'S1302 - Remittance towards personal gifts and donations',
        'RB-13.1-S1303': 'S1303 - Remittance towards donations to religious and charitable institutions abroad',
        'RB-13.1-S1304': 'S1304 - Remittance towards grants and donations to other governments and charitable institutions established by the',
        'RB-13.1-S1305': 'S1305 - Contributions/donations by the Government to international institutions',
        'RB-13.1-S1306': 'S1306 - Remittance towards payment / refund of taxes.',
        'RB-13.1-S1307': 'S1307 - Outflows on account of migrant transfers including personal'
    },
    'RB-14.1': {
        'RB-14.1-Select': 'Select',
        'RB-14.1-S1401': 'S1401 - Compensation of employees',
        'RB-14.1-S1402': 'S1402 - Remittance towards interest on Non-Resident deposits (FCNR(B)/NR(E)RA, etc.)',
        'RB-14.1-S1403': 'S1403 - Remittance towards interest on loans from Non-Residents (ST/MT/LT loans) e.g. External Commercial Borrowings,Trade Credits, etc.',
        'RB-14.1-S1405': 'S1405 - Remittance towards interest payment by ADs on their own account (to VOSTRO a/c holders or the OD on NOSTRO a/c.)',
        'RB-14.1-S1408': 'S1408 - Remittance of profit by FDI enterprises in India (by branches of foreign companies including bank branches)',
        'RB-14.1-S1409': 'S1409 - Remittance of dividends by FDI enterprises in India (other than branches) on equity and investment fund shares',
        'RB-14.1-S1410': 'S1410 - Payment of interest by FDI enterprises in India to their Parent company abroad.',
        'RB-14.1-S1411': 'S1411 - Remittance of interest income on account of Portfolio Investment in India',
        'RB-14.1-S1412': 'S1412 - Remittance of dividends on account of Portfolio Investment in India on equity and investment fund shares'
    },
    'RB-15.1': {
        'RB-15.1-Select': 'Select',
        'RB-15.1-S1501': 'S1501 - Refunds / rebates / reduction in invoice value on account of',
        'RB-15.1-S1502': 'S1502 - Reversal of wrong entries, refunds of amount remitted for non-Exports',
        'RB-15.1-S1503': 'S1503 - Payments by residents for international bidding',
        'RB-15.1-S1504': 'S1504 - Notional sales when export bills negotiated/ purchased/ discounted are dishonored/ crystallised/ cancelled and reversed from suspense account',
        'RB-15.1-S1505': 'S1505 - Deemed Imports (exports between SEZ, EPZs and Domestic tariff areas)'
    },
    'RB-16.1': {
        'RB-16.1-Select': 'Select',
        'RB-16.1-S1601': 'S1601 - Payments on account of maintenance and repair services rendered for Vessels, ships, boats, warships, etc.',
        'RB-16.1-S1602': 'S1602 - Payments on account of maintenance and repair services rendered for aircrafts, space shuttles, rockets, military aircrafts,'
    },
    'RB-17.1': {
        'RB-17.1-Select': 'Select',
        'RB-17.1-S1701': 'S1701 - Payments for processing of goods'
    },
    'Govt. not included elsewhere (G.n.i.e.)': {
        'RB-12.1.1': 'Govt. not included elsewhere (G.n.i.e.) - Other',
        'RB-12.1.2': 'Govt. not included elsewhere (G.n.i.e.) - Service payments',
    }
}


def get_rbi_purpose_code(category, specific_code):
    """
    Get the RBI purpose code for a given category and specific code.
    
    Args:
        category (str): The RBI purpose category (e.g., 'RB-1.1')
        specific_code (str): The specific code (e.g., 'RB-1.1-S0017')
        
    Returns:
        str: The description of the specific code, or None if not found
    """
    if category in RBI_PURPOSE_CODE_MAP and specific_code in RBI_PURPOSE_CODE_MAP[category]:
        return RBI_PURPOSE_CODE_MAP[category][specific_code]
    return None


def get_code(category, value):
    """
    Get the code for a given category and value.
    
    Args:
        category (str): The category of the mapping (e.g., 'examiner_prefix', 'country')
        value (str): The human-readable value to look up
        
    Returns:
        str: The corresponding code, or the original value if no mapping exists
    """
    mapping_dicts = {
        'examiner_prefix': EXAMINER_PREFIX_MAP,
        'remitter_prefix': REMITTER_PREFIX_MAP,
        'beneficiary_prefix': BENEFICIARY_PREFIX_MAP,
        'country': COUNTRY_MAP,
        'currency': CURRENCY_MAP,
        'bank': BANK_MAP,
        'nature_rem_category': NATURE_REM_CATEGORY_MAP,
        'rbi_purpose_category': RBI_PURPOSE_CATEGORY_MAP
    }

    if category not in mapping_dicts:
        return value

    # For nature remittance category and RBI purpose category, do case-insensitive lookup
    if category in ['nature_rem_category', 'rbi_purpose_category']:
        value_upper = value.upper()
        return mapping_dicts[category].get(value_upper, value)

    return mapping_dicts[category].get(value, value)
